{{- if and .Values.prometheus.enabled .Values.prometheus.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage
  namespace: {{ include "qwen3-8b-triton.namespace" . }}
  labels:
    {{- include "qwen3-8b-triton.prometheus.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.prometheus.storage.accessMode }}
  storageClassName: {{ .Values.prometheus.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.prometheus.storage.size }}
  volumeMode: Filesystem
{{- end }}

